export const SPREADSHEET_REGIONS = {
  // Super regions
  americas: "Americas",
  europe: "Europe",
  apac: "Asia Pacific",
  middle_east_africa: "Middle East & Africa",
  cis: "CIS",
  // Regions
  north_america: "North America",
  central_america: "Central America",
  caribbean: "Caribbean",
  south_america: "South America",
  western_europe: "Western Europe",
  eastern_europe: "Eastern Europe",
  northern_europe: "Northern Europe",
  southern_europe: "Southern Europe",
  east_asia: "East Asia",
  southeast_asia: "Southeast Asia",
  south_asia: "South Asia",
  oceania: "Oceania",
  sub_saharan_africa: "Sub-Saharan Africa",
  north_africa: "North Africa",
  middle_east: "Middle East",
  central_asia: "Central Asia",
  // Sub-regions
  nordic: "Nordic Countries",
  dach: "DACH",
  benelux: "Benelux",
  baltic: "Baltic States",
  mena: "MENA",
  gcc: "GCC",
  eea: "EEA",
  latam: "LATAM",
  asean: "ASEAN",
  // Special
  global: "Global",
} as const satisfies Readonly<Record<string, string>>

export const SPREADSHEET_NAMES = {
  // North America
  united_states: "United States",
  canada: "Canada",
  mexico: "Mexico",
  // Central America
  guatemala: "Guatemala",
  belize: "Belize",
  honduras: "Honduras",
  el_salvador: "El Salvador",
  nicaragua: "Nicaragua",
  costa_rica: "Costa Rica",
  panama: "Panama",
  // Caribbean
  cuba: "Cuba",
  haiti: "Haiti",
  dominican_republic: "Dominican Republic",
  jamaica: "Jamaica",
  trinidad_and_tobago: "Trinidad and Tobago",
  bahamas: "Bahamas",
  barbados: "Barbados",
  saint_lucia: "Saint Lucia",
  grenada: "Grenada",
  saint_vincent_and_the_grenadines: "Saint Vincent and the Grenadines",
  antigua_and_barbuda: "Antigua and Barbuda",
  dominica: "Dominica",
  saint_kitts_and_nevis: "Saint Kitts and Nevis",
  // South America
  brazil: "Brazil",
  argentina: "Argentina",
  colombia: "Colombia",
  peru: "Peru",
  venezuela: "Venezuela",
  chile: "Chile",
  ecuador: "Ecuador",
  bolivia: "Bolivia",
  paraguay: "Paraguay",
  uruguay: "Uruguay",
  guyana: "Guyana",
  suriname: "Suriname",
  // Western Europe
  germany: "Germany",
  france: "France",
  netherlands: "Netherlands",
  belgium: "Belgium",
  luxembourg: "Luxembourg",
  austria: "Austria",
  switzerland: "Switzerland",
  ireland: "Ireland",
  monaco: "Monaco",
  liechtenstein: "Liechtenstein",
  // Northern Europe
  united_kingdom: "United Kingdom",
  sweden: "Sweden",
  denmark: "Denmark",
  finland: "Finland",
  norway: "Norway",
  iceland: "Iceland",
  estonia: "Estonia",
  latvia: "Latvia",
  lithuania: "Lithuania",
  // Southern Europe
  italy: "Italy",
  spain: "Spain",
  portugal: "Portugal",
  greece: "Greece",
  croatia: "Croatia",
  slovenia: "Slovenia",
  malta: "Malta",
  cyprus: "Cyprus",
  andorra: "Andorra",
  san_marino: "San Marino",
  vatican_city: "Vatican City",
  north_macedonia: "North Macedonia",
  albania: "Albania",
  montenegro: "Montenegro",
  bosnia_and_herzegovina: "Bosnia and Herzegovina",
  serbia: "Serbia",
  // Eastern Europe
  poland: "Poland",
  czech_republic: "Czech Republic",
  romania: "Romania",
  hungary: "Hungary",
  slovakia: "Slovakia",
  bulgaria: "Bulgaria",
  ukraine: "Ukraine",
  moldova: "Moldova",
  belarus: "Belarus",
  // East Asia
  china: "China",
  japan: "Japan",
  south_korea: "South Korea",
  north_korea: "North Korea",
  mongolia: "Mongolia",
  taiwan: "Taiwan",
  // Southeast Asia
  indonesia: "Indonesia",
  thailand: "Thailand",
  vietnam: "Vietnam",
  philippines: "Philippines",
  malaysia: "Malaysia",
  singapore: "Singapore",
  myanmar: "Myanmar",
  cambodia: "Cambodia",
  laos: "Laos",
  brunei: "Brunei",
  timor_leste: "Timor-Leste",
  // South Asia
  india: "India",
  pakistan: "Pakistan",
  bangladesh: "Bangladesh",
  sri_lanka: "Sri Lanka",
  nepal: "Nepal",
  bhutan: "Bhutan",
  maldives: "Maldives",
  afghanistan: "Afghanistan",
  // Oceania
  australia: "Australia",
  new_zealand: "New Zealand",
  papua_new_guinea: "Papua New Guinea",
  fiji: "Fiji",
  solomon_islands: "Solomon Islands",
  vanuatu: "Vanuatu",
  samoa: "Samoa",
  kiribati: "Kiribati",
  tonga: "Tonga",
  micronesia: "Micronesia",
  palau: "Palau",
  marshall_islands: "Marshall Islands",
  tuvalu: "Tuvalu",
  nauru: "Nauru",
  // Middle East
  saudi_arabia: "Saudi Arabia",
  united_arab_emirates: "United Arab Emirates",
  qatar: "Qatar",
  kuwait: "Kuwait",
  bahrain: "Bahrain",
  oman: "Oman",
  iraq: "Iraq",
  iran: "Iran",
  israel: "Israel",
  jordan: "Jordan",
  lebanon: "Lebanon",
  syria: "Syria",
  yemen: "Yemen",
  palestine: "Palestine",
  turkey: "Turkey",
  // North Africa
  egypt: "Egypt",
  libya: "Libya",
  tunisia: "Tunisia",
  algeria: "Algeria",
  morocco: "Morocco",
  sudan: "Sudan",
  south_sudan: "South Sudan",
  western_sahara: "Western Sahara",
  // West Africa
  nigeria: "Nigeria",
  ghana: "Ghana",
  senegal: "Senegal",
  ivory_coast: "Ivory Coast",
  mali: "Mali",
  burkina_faso: "Burkina Faso",
  niger: "Niger",
  guinea: "Guinea",
  sierra_leone: "Sierra Leone",
  liberia: "Liberia",
  togo: "Togo",
  benin: "Benin",
  mauritania: "Mauritania",
  gambia: "Gambia",
  guinea_bissau: "Guinea-Bissau",
  cabo_verde: "Cabo Verde",
  // East Africa
  ethiopia: "Ethiopia",
  kenya: "Kenya",
  tanzania: "Tanzania",
  uganda: "Uganda",
  rwanda: "Rwanda",
  burundi: "Burundi",
  somalia: "Somalia",
  eritrea: "Eritrea",
  djibouti: "Djibouti",
  comoros: "Comoros",
  mauritius: "Mauritius",
  seychelles: "Seychelles",
  madagascar: "Madagascar",
  // Central Africa
  democratic_republic_of_the_congo: "Democratic Republic of the Congo",
  republic_of_the_congo: "Republic of the Congo",
  cameroon: "Cameroon",
  central_african_republic: "Central African Republic",
  chad: "Chad",
  gabon: "Gabon",
  equatorial_guinea: "Equatorial Guinea",
  sao_tome_and_principe: "Sao Tome and Principe",
  // Southern Africa
  south_africa: "South Africa",
  namibia: "Namibia",
  botswana: "Botswana",
  zimbabwe: "Zimbabwe",
  mozambique: "Mozambique",
  zambia: "Zambia",
  malawi: "Malawi",
  angola: "Angola",
  eswatini: "Eswatini",
  lesotho: "Lesotho",
  // Central Asia / CIS
  kazakhstan: "Kazakhstan",
  uzbekistan: "Uzbekistan",
  turkmenistan: "Turkmenistan",
  tajikistan: "Tajikistan",
  kyrgyzstan: "Kyrgyzstan",
  russia: "Russia",
  armenia: "Armenia",
  azerbaijan: "Azerbaijan",
  georgia: "Georgia",
  // Other / Disputed
  kosovo: "Kosovo",
  south_ossetia: "South Ossetia",
} as const satisfies Readonly<Record<string, string>>
